#!/usr/bin/env node
/**
 * Exposes MCP server via Streamable HTTP for web-based clients.
 * Uses Apps Extension (SEP-1865) for UI rendering.
 * 
 * Run with: npm run dev
 * Test with: npm run inspector:http
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express, { Request, Response } from "express";
import { z } from "zod";

import { SALES_UI } from "./ui/sales-form.js";
import { SALES_VISUALIZATION_UI } from "./ui/sales-visualization.js";
import { SALES_PDF_REPORT_UI } from "./ui/sales-pdf-report.js";
import { getData } from "./data/sales-data.js";
import { metricShortNames } from "./data/metric-names.js";
import { generateSalesPdf } from "./utils/generate-pdf.js";

const MIME = "text/html;profile=mcp-app" as const;
const URI = "ui://sample-mcp-apps-chatflow";

// Create MCP server with metadata
const server = new McpServer({
  name: "sample-mcp-apps-chatflow",
  version: "1.0.0",
});

// Register sales-metric-input-ui resource
server.registerResource(
  "sales-metric-input-ui",
  `${URI}/sales-metric-input-ui`,
  {
    mimeType: MIME,
    description: "Interactive sales metrics selector with regions, metrics, and time periods"
  },
  async (uri) => {
    console.log(`📱 resources/read called for: ${uri.href}`);
    return {
      contents: [
        {
          uri: uri.href,
          mimeType: MIME,
          text: SALES_UI(),
        },
      ],
    };
  }
);

// Register select-sales-metric tool
server.registerTool(
  "select-sales-metric",
  {
    description: "Tool to select input data for sales report generation and visualization. Interactive UI for selecting region, sales metrics (like revenue, orders, conversion rate, AOV, CLV, and more.) and time periods (monthly/quarterly).",
    _meta: {
      ui: {
        resourceUri: `${URI}/sales-metric-input-ui`,
        visibility: ["model", "app"],
      },
    },
  },
  async () => {
    console.error("[select-sales-metric] Tool executed");
    return {
      content: [{
        type: "text" as const,
        text: "Select Sales Metric Tool executed. Select input in the MCP App UI."
      }]
    };
  }
);

// =========================================
// App-only: Get Sales Data (callable by UI)
// =========================================

server.registerTool(
  "get-sales-data",
  {
    description: "Fetch sales report data for given states, metric, period, and year. Returns structured report with summary, period breakdown, and state-level data.",
    inputSchema: {
      states: z.array(z.string()).describe("Array of state codes (e.g. ['MH','TN','KA'])"),
      metric: z.string().describe("Metric key (e.g. 'revenue')"),
      period: z.enum(["monthly", "quarterly"]).describe("Period granularity"),
      year: z.string().describe("Year for the report"),
    },
    _meta: {
      ui: {
        resourceUri: `${URI}/sales-metric-input-ui`,
        visibility: ["app"],
      },
    },
  },
  async ({ states, metric, period, year }) => {
    console.log(`🔧 [get-sales-data] metric=${metric}, period=${period}, year=${year}, states=${states.join(',')}`);
    const report = getData(states, metric, period as 'monthly' | 'quarterly', year);
    console.log(JSON.stringify(report, null, 2));
    return {
      content: [{ type: "text" as const, text: JSON.stringify(report) }],
      structuredContent: report as unknown as Record<string, unknown>,
    };
  }
);

// =========================================
// Sales Visualization (Charts)
// =========================================

server.registerResource(
  "sales-data-visualization-ui",
  `${URI}/sales-visualization`,
  {
    mimeType: MIME,
    description: "Interactive sales data visualization with charts",
  },
  async (uri) => {
    console.log(`📱 resources/read called for: ${uri.href}`);
    return {
      contents: [
        {
          uri: uri.href,
          mimeType: MIME,
          text: SALES_VISUALIZATION_UI(),
          _meta: {
            ui: {
              csp: {
                resourceDomains: ["https://cdn.jsdelivr.net"],
              },
              prefersBorder: false,
            },
          },
        },
      ],
    };
  }
);

server.registerTool(
  "visualize-sales-data",
  {
    description: "Visualize sales report data as interactive charts (bar, line, doughnut). Accepts the structured data previously generated by sales_metric_selector. Shows period breakdown, state distribution, and state comparison charts.",
    inputSchema: {
      selections: z.object({
        states: z.array(z.string()).describe("Array of state codes"),
        metric: z.string().describe("Metric key (e.g. 'revenue')"),
        period: z.enum(["monthly", "quarterly"]).describe("Period granularity"),
        year: z.string().describe("Year"),
      }).describe("The selections object from sales_metric_selector output"),
      report: z.object({
        summary: z.object({
          total: z.string(),
          average: z.string(),
          trend: z.string(),
          totalRaw: z.number(),
          averageRaw: z.number(),
        }),
        topState: z.object({
          name: z.string(),
          code: z.string(),
          value: z.string(),
          percentage: z.string(),
        }),
        periods: z.array(z.object({
          period: z.string(),
          total: z.string(),
          stateValues: z.record(z.string(), z.number()),
        })),
        states: z.array(z.object({
          state: z.string(),
          value: z.string(),
          percentage: z.string(),
        })),
        stateNames: z.array(z.string()).describe("Ordered state names for column headers"),
      }).describe("The report object from sales_metric_selector output"),
    },
    _meta: {
      ui: {
        resourceUri: `${URI}/sales-visualization`,
        visibility: ["model", "app"],
      },
    },
  },
  async ({ selections, report }, extra) => {
    console.log('🔧 Tool visualize-sales-data called: metric=${selections.metric}, period=${selections.period}, year=${selections.year}');
    const metricName = metricShortNames[selections.metric] || selections.metric;
    const periodText = selections.period === 'monthly' ? 'Monthly' : 'Quarterly';
    console.log('🔧 Tool visualize-sales-data input:');
    console.log(JSON.stringify(report, null, 2));
    return {
      content: [{
        type: "text" as const,
        text: `📊 Sales visualization rendered for ${metricName} (${periodText}, ${selections.year}) across ${selections.states.length} states.`
      }],
      structuredContent: {
        selections,
        report,
      },
    };
  }
);

// =========================================
// Sales PDF Report
// =========================================

server.registerResource(
  "sales-pdf-report-ui",
  `${URI}/sales-pdf-report`,
  {
    mimeType: MIME,
    description: "PDF report download UI for sales data",
  },
  async (uri) => {
    console.log(`📱 resources/read called for: ${uri.href}`);
    return {
      contents: [
        {
          uri: uri.href,
          mimeType: MIME,
          text: SALES_PDF_REPORT_UI(),
          _meta: {
            ui: {
              prefersBorder: false,
              csp: {
                resourceDomains: ["https://cdn.jsdelivr.net"],
              },
            },
          },
        },
      ],
    };
  }
);

server.registerTool(
  "show-sales-pdf-report",
  {
    description: "Generate a downloadable PDF report with tables and charts from sales data. Accepts the structured data previously generated by sales_metric_selector. The PDF includes summary table, period breakdown chart and table, and state comparison chart and table.",
    inputSchema: {
      selections: z.object({
        states: z.array(z.string()).describe("Array of state codes"),
        metric: z.string().describe("Metric key (e.g. 'revenue')"),
        period: z.enum(["monthly", "quarterly"]).describe("Period granularity"),
        year: z.string().describe("Year"),
      }).describe("The selections object from sales_metric_selector output"),
      report: z.object({
        summary: z.object({
          total: z.string(),
          average: z.string(),
          trend: z.string(),
          totalRaw: z.number(),
          averageRaw: z.number(),
        }),
        topState: z.object({
          name: z.string(),
          code: z.string(),
          value: z.string(),
          percentage: z.string(),
        }),
        periods: z.array(z.object({
          period: z.string(),
          total: z.string(),
          stateValues: z.record(z.string(), z.number()),
        })),
        states: z.array(z.object({
          state: z.string(),
          value: z.string(),
          percentage: z.string(),
        })),
        stateNames: z.array(z.string()).describe("Ordered state names for column headers"),
      }).describe("The report object from sales_metric_selector output"),
    },
    _meta: {
      ui: {
        resourceUri: `${URI}/sales-pdf-report`,
        visibility: ["model", "app"],
      },
    },
  },
  async ({ selections, report }, extra) => {
    const metricName = metricShortNames[selections.metric] || selections.metric;
    const periodText = selections.period === 'monthly' ? 'Monthly' : 'Quarterly';

    console.log(`🔧 Tool show-sales-pdf-report called: metric=${selections.metric}, period=${selections.period}, year=${selections.year}`);

    const { base64, fileName, fileSize } = generateSalesPdf(selections, report, metricName);
    console.log(`📄 PDF generated: ${fileName} (${fileSize} bytes)`);

    return {
      content: [{
        type: "text" as const,
        text: `📄 PDF report generated for ${metricName} (${periodText}, ${selections.year}) across ${selections.states.length} states. Use the download button in the UI to save it.`
      }],
      structuredContent: {
        pdfBase64: base64,
        fileName,
        fileSize,
        title: `${metricName} · ${periodText} · ${selections.year}`,
      },
    };
  }
);

// Express app for HTTP transport
const app = express();
app.use(express.json());

// Health check endpoint
app.get("/health", (_req: Request, res: Response) => {
  res.json({ status: "ok", server: "sample-mcp-apps-chatflow" });
});

// MCP endpoint
app.post("/mcp", async (req: Request, res: Response) => {
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true,
  });

  res.on("close", () => transport.close());

  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
});

// SSE endpoint for streaming (optional)
app.get("/mcp/sse", async (req: Request, res: Response) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");

  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: () => crypto.randomUUID(),
    enableJsonResponse: false,
  });

  res.on("close", () => transport.close());

  await server.connect(transport);
  await transport.handleRequest(req, res);
});

const port = parseInt(process.env.PORT || "3000");

app.listen(port, () => {
  console.log(`🚀 MCP Apps Chatflow server running at http://localhost:${port}`);
  console.log(`📡 MCP endpoint: http://localhost:${port}/mcp`);
  console.log(`🔍 Test with: npx @modelcontextprotocol/inspector http://localhost:${port}/mcp`);
});
